### ISSUE TITLE
Please refactor "Languaje"

### ISSUE THREAD

**Issue by realhackcraft** [yossTheDev/karbonized#1]
Languaje is incorrect. It should be "language."

**Comment by realhackcraft** [comment]
![ccd4c41cb392742247f048d2aaeca9f6](https://user-images.githubusercontent.com/65378120/232356676-6a3cab18-5a37-43ee-8a5a-d670d05b70b9.png)

**Comment by yossdotpro** [comment]
Yes, you are right, sorry 🙏 let me fix this

**Comment by realhackcraft** [comment]
Thank you! :)

**Comment by realhackcraft** [comment]
After the fix, i will probably clone this to use it offline.
